[package]
version = "0.1.0"
name = "host"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "env"] }
tokio.workspace = true
tracing-subscriber = "0.3.18"
dotenv = "0.15.0"
eyre = "0.6.12"

# workspace
host-executor.workspace = true
primitives.workspace = true
provider.workspace = true

# zkMIPS
zkm-sdk.workspace = true

[dev-dependencies]
alloy-network.workspace = true
guest-executor.workspace = true
serde_json = "1.0"
thousands = "0.2.0"
madato = "0.7.0"

[build-dependencies]
zkm-build.workspace = true
