[package]
name = "host-executor"
description = ""
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
csv = "1.1"
clap = { version = "4.5.7", features = ["derive", "env"] }
tokio = { workspace = true, features = ["time", "rt"] }
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
url.workspace = true
reqwest = { workspace = true, features = ["json"], optional = true }
eyre = "0.6.12"
bincode = "1.3.3"
either = "1.13.0"
strum = "0.26"
sha2 = "0.10.8"
hex = "0.4.3"

# workspace
rpc-db.workspace = true
guest-executor = { workspace = true, features = ["optimism"] }
mpt = { workspace = true }
primitives = { workspace = true, features = ["optimism"] }

# Ziren
zkm-core-executor.workspace = true
zkm-sdk.workspace = true
zkm-prover.workspace = true

# reth
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-optimism-evm = { workspace = true }
reth-optimism-chainspec = { workspace = true }
reth-optimism-primitives.workspace = true
reth-ethereum-primitives.workspace = true
reth-primitives-traits = { workspace = true, features = ["secp256k1"] }
reth-trie.workspace = true
reth-trie-common.workspace = true
reth-execution-types.workspace = true
reth-errors.workspace = true
reth-chainspec.workspace = true
reth-stateless.workspace = true
reth-trie-zkvm.workspace = true

# revm
revm-bytecode.workspace = true
revm.workspace = true
revm-primitives.workspace = true

# alloy
alloy-chains.workspace = true
alloy-consensus.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
alloy-rpc-types.workspace = true
alloy-eips.workspace = true
alloy-rlp.workspace = true

# op
op-alloy-network.workspace = true
futures = "0.3.31"

[dev-dependencies]
alloy-primitives.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
bincode = "1.3.3"
dotenv = "0.15.0"

[features]
default = ["execution-witness"]
alerting = ["dep:reqwest"]
execution-witness = [
    "mpt/execution-witness",
    "rpc-db/execution-witness",
]
